name: bug-mkt
region: fra
features:
  - buildpack-stack=ubuntu-22
services:
  - name: bugetare
    http_port: 8080
    source_dir: /
    dockerfile_path: /Dockerfile
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    github:
      repo: sebastiansabo/Bugetare
      branch: main
      deploy_on_push: true
    envs:
      - key: ANTHROPIC_API_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: GOOGLE_CREDENTIALS_JSON
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        type: SECRET
        scope: RUN_TIME
ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: bugetare
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
