"""Monthly voucher digest email builder."""
import logging
from datetime import date

logger = logging.getLogger('jarvis.vouchers.digest')


def build_digest_html(digest_data: dict, company_name: str, ref_date: date) -> str:
    """Build HTML for the monthly voucher digest email."""
    s = digest_data.get('summary', {})
    per_user = digest_data.get('per_user', [])
    month_label = ref_date.strftime('%B %Y')

    html = f"""
    <h2>Voucher Monthly Digest &mdash; {month_label}</h2>
    <p>Company: <strong>{company_name}</strong></p>

    <h3>Company Summary</h3>
    <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse;">
        <tr><td>Active Vouchers</td><td><strong>{s.get('active_count', 0)}</strong></td></tr>
        <tr><td>Active Total Value (LEI)</td><td><strong>{s.get('active_total_value', 0)}</strong></td></tr>
        <tr><td>Redeemed Last Month</td><td>{s.get('redeemed_last_month', 0)} (Value: {s.get('redeemed_last_month_value', 0)} LEI)</td></tr>
        <tr><td>Expired Last Month</td><td>{s.get('expired_last_month', 0)}</td></tr>
        <tr><td>Expiring This Month</td><td>{s.get('expiring_this_month', 0)}</td></tr>
        <tr><td>New Last Month</td><td>{s.get('new_last_month', 0)}</td></tr>
    </table>

    <h3>Per-User Breakdown</h3>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;">
        <tr style="background:#f0f0f0;">
            <th>User</th><th>Active</th><th>Active Value</th>
            <th>Redeemed</th><th>Expired</th><th>Pending</th><th>Expiring This Month</th>
        </tr>
    """

    for u in per_user:
        html += f"""
        <tr>
            <td>{u.get('user_name', '')}</td>
            <td>{u.get('active_count', 0)}</td>
            <td>{u.get('active_value', 0)} LEI</td>
            <td>{u.get('redeemed_count', 0)}</td>
            <td>{u.get('expired_count', 0)}</td>
            <td>{u.get('pending_count', 0)}</td>
            <td>{u.get('expiring_this_month', 0)}</td>
        </tr>
        """

    html += """
    </table>
    <p style="color:#888;font-size:12px;">Generated by JARVIS Voucher Module</p>
    """
    return html


def send_monthly_digest():
    """Send monthly voucher digest to all users. Called by scheduler."""
    try:
        from accounting.vouchers.repositories import VoucherRepository
        from core.base_repository import BaseRepository
        from core.services.notification_service import send_email

        repo = VoucherRepository()
        base = BaseRepository()

        # Get all companies that have vouchers
        companies = base.query_all('''
            SELECT DISTINCT c.id, c.name
            FROM companies c
            JOIN vouchers v ON v.company_id = c.id
        ''')

        for company in companies:
            digest_data = repo.get_digest_data(company['id'], date.today())
            if not digest_data.get('per_user'):
                continue

            html = build_digest_html(digest_data, company['name'], date.today())

            # Send to each user who has vouchers
            for u in digest_data['per_user']:
                email = u.get('user_email')
                if email:
                    try:
                        send_email(
                            to_email=email,
                            subject=f"Voucher Monthly Digest -- {date.today().strftime('%B %Y')}",
                            html_body=html,
                        )
                    except Exception:
                        logger.exception('Failed to send digest to %s', email)

        logger.info('Monthly voucher digest sent')
    except Exception:
        logger.exception('Failed to run monthly voucher digest')
