-- Migration 005: Switch from per-company to per-group adjustments
--
-- Previously, multi-contract employees had adjustments stored under ONE buid
-- with company_name differentiating them.  Now each group's buid gets its own
-- adjustment row (company_name is no longer used).
--
-- 1. Delete all per-company adjustment rows (company_name IS NOT NULL).
--    They will be regenerated by auto-adjust using the new per-group logic.
-- 2. For multi-contract employees, delete duplicate global adjustments
--    (multiple buids × same jarvis_user × same date with company_name IS NULL).
--    Keep only one per (jarvis_user, date) — the one with the latest updated_at.
-- 3. Drop the COALESCE-based functional unique index.
-- 4. Restore the simple (biostar_user_id, date) unique constraint.

-- Step 1: Remove per-company adjustment rows
DELETE FROM biostar_daily_adjustments WHERE company_name IS NOT NULL;

-- Step 2: Remove duplicate global adjustments for multi-contract employees
-- Keep the most recently updated row per (jarvis_user, date)
DELETE FROM biostar_daily_adjustments
WHERE id NOT IN (
    SELECT DISTINCT ON (be.mapped_jarvis_user_id, adj.date) adj.id
    FROM biostar_daily_adjustments adj
    JOIN biostar_employees be ON be.biostar_user_id = adj.biostar_user_id
    WHERE be.mapped_jarvis_user_id IS NOT NULL
    ORDER BY be.mapped_jarvis_user_id, adj.date, adj.updated_at DESC NULLS LAST
)
AND biostar_user_id IN (
    SELECT biostar_user_id FROM biostar_employees WHERE mapped_jarvis_user_id IS NOT NULL
);

-- Step 3: Drop the functional unique index added by migration 004
DROP INDEX IF EXISTS uq_biostar_adj_user_date_company;

-- Step 4: Add simple unique constraint (one adjustment per buid per date)
ALTER TABLE biostar_daily_adjustments
    ADD CONSTRAINT uq_biostar_adj_user_date UNIQUE (biostar_user_id, date);

-- Step 5: Drop company_name column (no longer used)
ALTER TABLE biostar_daily_adjustments DROP COLUMN IF EXISTS company_name;
